// Q.1 Convert to Uppercase (toUpperCase())
// Q.2 Convert to Lowercase (toLowerCase())
// Q.3 Extract a Substring (substring() or slice())
// Q.4  Trim Whitespace (trim())
// Q.5 Check if String Contains a Substring (includes())
// Q.6  Replace Part of a String (replace())
// Q.7 Split a String into an Array (split())
// Q.8 Join an Array into a String (join())
// Q.9 Get Character at a Specific Index (charAt())
// Q.10 Check String Starts or Ends with Substring (startsWith(), endsWith())